[package]
name = "trss-import"
version.workspace = true
edition.workspace = true

[dependencies]
trss-anissia.workspace = true
trss-collect.workspace = true
trss-core.workspace = true

regex.workspace = true
serde = { workspace = true, features = ["derive"] }
yaml_serde.workspace = true
url.workspace = true
