services:
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Seoul
    volumes:
      - ${TRANSMISSION_CONFIG_DIR:?Set TRANSMISSION_CONFIG_DIR in .env}:/config
      - ${DOWNLOADS_DIR:?Set DOWNLOADS_DIR in .env}:/downloads
      - ${WATCH_DIR:?Set WATCH_DIR in .env}:/watch
    ports:
      - "9091:9091"
      # - "51413:51413"
      # - "51413:51413/udp"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 128M
    restart: unless-stopped
    networks:
      - trss_net

networks:
  trss_net:
    name: trss_net
