[package]
name = "trss-transmission"
version.workspace = true
edition.workspace = true

[dependencies]
trname.workspace = true

regex.workspace = true
reqwest012.workspace = true
tokio = { workspace = true, features = ["macros", "time"] }
tokio-util.workspace = true
transmission-rpc.workspace = true
url.workspace = true
