[package]
name = "trss-subtitles"
version.workspace = true
edition.workspace = true

[dependencies]
bytes.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["time"] }
url.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "time"] }
