pub mod anissia;
pub mod archive_suggestions;
pub mod artwork;
pub mod automatic_watch;
pub mod config;
pub mod discovery;
pub mod episode_offset;
pub mod folders;
pub mod import;
pub mod rss;
pub mod rule;
pub mod schedule;
pub mod seasons;
pub mod store;
pub mod subscriptions;
pub mod transmission;
pub mod web;
pub mod worker;

pub const USER_AGENT: &str = "trss/0.3";
